package uz.javachi.devops_assignment.service;

import io.micrometer.core.annotation.Timed;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import uz.javachi.devops_assignment.model.User;
import uz.javachi.devops_assignment.repository.UserRepository;

import java.time.LocalDateTime;
import java.util.List;

@Slf4j
@Service
public class UserService {

    private final UserRepository userRepository;
    private final Timer databaseQueryTimer;

    public UserService(UserRepository userRepository, MeterRegistry meterRegistry) {
        this.userRepository = userRepository;
        
        // Gauge metric - real-time user count
        Gauge.builder("users.active.count", userRepository, UserRepository::count)
                .description("Current number of users in system")
                .tag("type", "active")
                .register(meterRegistry);
        
        // Timer metric - database query time
        this.databaseQueryTimer = Timer.builder("users.database.query.time")
                .description("Time taken for database queries")
                .tag("operation", "query")
                .register(meterRegistry);
    }

    @Timed(value = "users.service.getAll", description = "Time to fetch all users")
    public List<User> getAllUsers() {
        return databaseQueryTimer.record(() -> {
            log.info("Getting all users. Current count: {}", userRepository.count());
            return userRepository.findAll();
        });
    }

    @Timed(value = "users.service.getById", description = "Time to fetch user by ID")
    public User getUserById(String id) {
        return databaseQueryTimer.record(() -> {
            if (id == null || id.trim().isEmpty()) {
                throw new RuntimeException("User ID cannot be null or empty");
            }
            
            log.info("Getting user by id: {}", id);
            return userRepository.findById(id).orElse(null);
        });
    }

    @Timed(value = "users.service.create", description = "Time to create user")
    public User createUser(User user) {
        return databaseQueryTimer.record(() -> {
            if (user == null) {
                throw new RuntimeException("User cannot be null");
            }
            
            if (user.getEmail() == null || user.getEmail().trim().isEmpty()) {
                throw new RuntimeException("Email is required");
            }
            
            // Always set uuid to null for new user to avoid merge conflicts
            // UUID will be auto-generated by @GeneratedValue(strategy = GenerationType.UUID)
            user.setUuid(null);
            
            // Email unique bo'lishi kerak
            if (userRepository.existsByEmail(user.getEmail())) {
                throw new RuntimeException("User with email " + user.getEmail() + " already exists");
            }
            user.setCreatedAt(LocalDateTime.now());
            
            User saved = userRepository.save(user);
            log.info("Created new user: {} (Total: {})", user.getName(), userRepository.count());
            return saved;
        });
    }

    public long getUserCount() {
        return userRepository.count();
    }
    
    public User getUserByEmail(String email) {
        if (email == null || email.trim().isEmpty()) {
            throw new RuntimeException("Email cannot be null or empty");
        }
        return userRepository.findByEmail(email).orElse(null);
    }
}
